package com.florian;

public enum ErrorCode {
    SUCCESS, UNKNOWN_COMMAND, UNKNOWN_ID, WRONG_ARGUMENTS, NO_PERMISSION, UNALLOWED_CHARACTER, UNINITIALIZED_COMMAND, UNKNOWN_OPERATION, NO_USER_HISTORY, UNKNOWN_ENTRY, OTHER_ERROR
}

