package com.florian;

public enum ErrorCode {
    SUCCESS, UNKNOWN_COMMAND, UNKNOWN_ID, WRONG_ARGUMENTS, NO_PERMISSION, UNINITIALIZED_COMMAND, UNKNOWN_OPERATION, NO_USER_HISTORY, UNKNOWN_ENTRY, QUESTION_TOO_LONG, NO_REMINDERS, REMINDER_TOO_SHORT, NO_USER_LOG, TOO_MUCH_HISTORY, TOO_MANY_REMINDERS, PREFIX_TOO_LONG, NO_SCORES, NO_ROLE_REWARDS, TOO_MANY_ROLE_REWARDS, INVALID_SCORE, COMMAND_DISABLED, UNKNOWN_COMMAND_NAME, CANNOT_BE_DISABLED, INPUT_TOO_LONG, NO_LOGS, OTHER_ERROR
}

