package com.florian;

public enum ErrorCode {
    SUCCESS, UNKNOWN_COMMAND, UNKNOWN_ID, WRONG_ARGUMENTS, NO_PERMISSION, UNINITIALIZED_COMMAND, UNKNOWN_OPERATION, NO_USER_HISTORY, UNKNOWN_ENTRY, QUESTION_TOO_LONG, NO_REMINDERS, REMINDER_TOO_SHORT, NO_USER_LOG, OTHER_ERROR
}

